### ISSUE TITLE
Can't connect to WS after launching separate headless chrome instance

### ISSUE THREAD

**Issue by bsyouness** [jupyterlab/galata#59]
## Description
I'm able to run galata fine as long as I don't specify my own browser. Otherwise the process just hangs. I've tried running:
```
node ./node_modules/.bin/galata "--browser-url" "http://localhost:9222" --browser-type chromium
```

This might be related to this issue: https://github.com/microsoft/playwright/issues/4054
But I've tried replacing `connect` in Galata source code with `connectOverCDP` but without success.

**Comment by mbektas** [comment]
@bsyouness I am able to reproduce the issue. Looks like we need to handle remote connection to chromium browser specially.

**Comment by dharmaquark** [comment]
@mbektas any local workaround you could suggest? Or could we help in pushing a patch upstream to address?

**Comment by mbektas** [comment]
Hi @dharmaquark and @bsyouness! I have been looking into this issue. I have a solution that seems to work for remote connected and new browser instances for `chromium`. Created this PR (https://github.com/jupyterlab/galata/pull/66) with my changes, please test it well and push your additional changes to that branch. I didn't get chance to test thoroughly and with other browser types.

**Comment by bsyouness** [comment]
Awesome! I will test soon and keep you posted. Thank you so much @mbektas !!

**Comment by legendb317** [comment]
Hi @mbektas. We have tested the [PR](https://github.com/jupyterlab/galata/pull/66) with `chromium` and the process no longer hangs. Thank you for fixing this issue.

**Comment by mbektas** [comment]
hi @legendb317 thanks! We also need to test with Firefox (`--browser-type firefox`) and Microsoft Edge (`--browser-type chromium --browser-path /path/to/edge"`) before merging. Would you have some time to do that testing?

**Comment by legendb317** [comment]
Hi! @mbektas. Yeah I will do some testing and get back to you. Thank you!

**Comment by legendb317** [comment]
Hi @mbektas. I have tested with `chrome` and `edge` and everything works as expected. However, I was not able to successfully test `firefox`. The process hangs here:
https://github.com/jupyterlab/galata/blob/610f1ba72614076a72a854c2893806f33c42041b/packages/galata/jest-setup.js#L76 Upon further investigation, it seems that `firefox` has an issue with setting up a remote debugging port. To reproduce the issue, I set up an alias for `firefox` using `alias firefox=/Applications/Firefox.app/Contents/MacOS/firefox`. Next, I enabled add-on debugging toolboxes and remote debugging in the browser. Finally, I ran `firefox --remote-debugging-port` which outputs a `ws` link that DevTools is listening on. When placing this link into a browser, it does not load. I suspect this to be the reason why the `pwBrowser.connectOverCDP` never resolves. 

There seems to be an issue with `firefox` rather than Galata. Does it make sense to open a separate issue to investigate this further so that we do not hold up the fix with `chromium` browsers?

**Comment by bsyouness** [comment]
+1
I also tried to run `firefox --remote-debugging-port` and saw the same symptoms as Legend. I think it makes sense to patch this in to get something working and tackle the Firefox issue separately. I would also report the issue to Mozilla so they can assist.
